workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      node: 20
      vars:
        PROJECT_PATH: mobile
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_PATH
          npm install
      - name: Build Android debug APK
        script: |
          cd $PROJECT_PATH/android
          ./gradlew assembleDebug
    artifacts:
      - mobile/android/app/build/outputs/**/*.apk